### ISSUE TITLE
storableSetGet uses wrong bounds on list

### ISSUE THREAD

**Issue by ag-eitilt** [chessai/hedgehog-classes#18]
Rather than using the `genSmallNonEmptyList` that `storableGetSet` does, `storableSetGet` [generates the length of the list](https://github.com/chessai/hedgehog-classes/blob/48ef293f80283227dd0f463ba12fb1a124f1d7c4/src/Hedgehog/Classes/Storable.hs#L106) independently, and then uses that number to generate its array of test objects.  However, it does so in a way that allows *empty* lists, which then throw everything off culminating in `malloc` errors crashing the test suite.  The solution seems to be simply changing the `0` on that line to `1`; I didn't want to go through an entire branch+PR cycle for a single-byte change.

**Comment by chessai** [comment]
Fixed, thanks!
